version: 2

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - "-s"
      - "-X=github.com/synackd/ochami/internal/version.Version={{ .Version }} \
         -X=github.com/synackd/ochami/internal/version.Commit={{ .Commit }} \
         -X=github.com/synackd/ochami/internal/version.Date={{ .Date }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE

dockers:
  - dockerfile: goreleaser.dockerfile
    image_templates:
      - &amd64_linux_image ghcr.io/synackd/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/synackd/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/synackd/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - LICENSE
  - dockerfile: goreleaser.dockerfile
    image_templates:
      - &arm64v8_linux_image ghcr.io/synackd/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/synackd/{{ .ProjectName }}:v{{ .Major }}-arm64
      - ghcr.io/synackd/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - LICENSE

docker_manifests:
  - name_template: "ghcr.io/synackd/{{ .ProjectName }}:latest"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image
  - name_template: "ghcr.io/synackd/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image
  - name_template: "ghcr.io/synackd/{{ .ProjectName }}:{{ .Major }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image
  - name_template: "ghcr.io/synackd/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:print:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:print:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:print:]]+\))??!?:.+$'
      order: 2
    - title: Build System
      regexp: '^.*?(build|ci)(\([[:print:]]+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
  name_template: "v{{ .Version }}"
  prerelease: auto
  mode: replace
