################################################################################
#
# GLOBAL OPTIONS
#
################################################################################

# Specify how ochami should log
log:
  # Log level. Specify how verbose ochami should be. Available values are:
  #
  # info
  # warning (default)
  # debug
  level: warning

  # Log format. Specify the format of log messages. Available values are:
  #
  # json (default)
  # rfc3339 - Follows formatting in RFC 3339
  # basic   - Specifies log level but no timestamp data
  format: json

# Specify the name of the cluster to use by default. If this is not specified,
# --cluster must be used on the command line to specify the name of the cluster
# to use when communicating with OpenCHAMI services.
#
# The directive below is commented out in case this file is used as an actual
# config file.
#default-cluster: local

################################################################################
#
# CLUSTER-SPECIFIC OPTIONS
#
################################################################################

# The clusters block specify a list of cluster configurations that can be used
# by ochami. Each item in the cluster list has the following keys:
#
# name    - The user-defined name of the cluster. This is what is used by
#           default-cluster above and --cluster on the CLI.
# cluster - The block containing the actual cluster configuration.
#
# The cluster block can contain the following keys:
#
# base-uri - The URI of the API gateway behind which the OpenCHAMI services are
#            listening. ochami will append to this URI the base path for the
#            service being communicated with as well as the endpoint being used.
#
# Below is an example of a clusters block, commented out in case this
# file is used as an actual config.
#
#clusters:
#    - name: foobar
#      cluster:
#        base-uri: https://foobar.si.usrc
#    - name: local
#      cluster:
#        base-uri: https://local.openchami.cluster:8443
