name: Run unit tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up latest stable Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: 1
          fetch-depth: 0
      - name: Run Go unit tests
        run: go test ./...
